version: "3.5"
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    deploy:
      placement:
        constraints:
          - "node.role==manager"
    networks:
     - kafka-network
  kafka1:
    image: wurstmeister/kafka:latest
    deploy:
      placement:
        constraints:
          - "node.role==worker"
    networks:
     - kafka-network
    ports:
      - target: 9093
        published: 9093
        protocol: tcp
        mode: host
    environment:
      HOSTNAME_COMMAND: "ip -4 addr show enp0s8 | grep -oP '(?<=inet\\s)\d+(\\.\\d+){3}' | head -1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9093
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  kafka-network: